sudo: required
services:
  - Docker

before_install:
  - docker build -t dronavallisuhas/docker-react -f Dockerfile.dev .

script:
  - docker run dronavallisuhas/docker-react npm run test -- --coverage
